import { Grid, GridItem } from "@chakra-ui/react";
import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import { fonts } from "./fonts";
import "./globals.css";
import { Providers } from "./providers";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "SkillBoost Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fonts.inter.variable}>
        <Providers>
          <Grid
            templateAreas={{
              base: `"nav" "main" "footer"`,
              lg: `"nav nav" "main" "footer"`,
            }}
            templateColumns={{
              base: "1fr",
            }}
          >
            <GridItem area="nav">
              <NavBar />
            </GridItem>
            <GridItem area="main" m={5}>
              <main>{children}</main>
            </GridItem>
            <GridItem area="footer">
              <Footer />
            </GridItem>
          </Grid>
        </Providers>
      </body>
    </html>
  );
}
