import type { Metadata } from "next";
import { fonts } from "./fonts";
import "./globals.css";
import { Providers } from "./providers";
import { Grid, GridItem, Show } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "SkillBoost Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fonts.inter.variable}>
        <Providers>
          <Grid
            templateAreas={{
              base: `"nav" "main"`,
              lg: `"nav nav" "main"`,
            }}
            templateColumns={{
              base: "1fr",
            }}
          >
            <GridItem area="nav" bg="red">
              Nav
            </GridItem>
            <GridItem area="main" bg="blue">
              <main>{children}</main>
            </GridItem>
          </Grid>
        </Providers>
      </body>
    </html>
  );
}
